esphome:
  name: luz-de-natal
  friendly_name: Luz de Natal

esp8266:
  board: d1

logger:

api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

# ------------------------------------
# TIME (NTP)
# ------------------------------------
time:
  - platform: sntp
    id: horario_atual
    timezone: America/Sao_Paulo
    servers:
      - a.st1.ntp.br

    # LIGA às 18:00
    on_time:
      - seconds: 0
        minutes: 0
        hours: 18
        then:
          - logger.log: "⚡ Relés LIGADOS (Noite)"
          - switch.turn_on: rele_1
          - switch.turn_on: rele_2
          - switch.turn_on: rele_3

      # DESLIGA às 06:00
      - seconds: 0
        minutes: 0
        hours: 6
        then:
          - logger.log: "💤 Relés DESLIGADOS (Dia)"
          - switch.turn_off: rele_1
          - switch.turn_off: rele_2
          - switch.turn_off: rele_3

# ------------------------------------
# RELÉS
# ------------------------------------
switch:
  - platform: gpio
    name: "Relé 1"
    id: rele_1
    pin:
      number: D5
      inverted: true   # Relé ativo em LOW
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Relé 2"
    id: rele_2
    pin:
      number: D6
      inverted: true
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Relé 3"
    id: rele_3
    pin:
      number: D7
      inverted: true
    restore_mode: ALWAYS_OFF
