esphome:
  name: luz-de-natal

esp8266:
  board: nodemcuv2

wifi:
  ssid: ""     // *** MUDAR AQUI *** Nome da sua rede Wi-Fi
  password: "" // *** MUDAR AQUI *** Senha da sua rede Wi-Fi
  min_auth_mode: WPA2

logger:
ota:

time:
  - platform: sntp
    timezone: America/Sao_Paulo
    servers:
      - a.st1.ntp.br

    on_time:
      - seconds: 0
        minutes: 0
        hours: 18
        then:
          - switch.turn_on: rele_1
          - switch.turn_on: rele_2
          - switch.turn_on: rele_3

      - seconds: 0
        minutes: 0
        hours: 6
        then:
          - switch.turn_off: rele_1
          - switch.turn_off: rele_2
          - switch.turn_off: rele_3

switch:
  - platform: gpio
    name: "Relé 1"
    id: rele_1
    pin:
      number: D5
      inverted: true
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Relé 2"
    id: rele_2
    pin:
      number: D6
      inverted: true
    restore_mode: ALWAYS_OFF

  - platform: gpio
    name: "Relé 3"
    id: rele_3
    pin:
      number: D7
      inverted: true
    restore_mode: ALWAYS_OFF
